import { oc, eventIterator } from "@orpc/contract";
import {
  // Session
  sessionCreateInput,
  sessionCreateOutput,
  sessionListInput,
  sessionListOutput,
  sessionLoadInput,
  sessionLoadOutput,
  sessionDeleteInput,
  sessionDeleteOutput,
  sessionRenameInput,
  sessionRenameOutput,
  // Agent
  agentListOutput,
  agentPromptInput,
  agentPromptOutput,
  agentAbortInput,
  agentAbortOutput,
  agentStatusInput,
  agentStatusOutput,
  agentOnEventsInput,
  agentEventSchema,
  agentShellExecInput,
  agentShellExecOutput,
  // Tool
  toolListInput,
  toolListOutput,
  toolApproveInput,
  toolApproveOutput,
  toolDenyInput,
  toolDenyOutput,
  // Worker
  workerRegisterInput,
  workerRegisterOutput,
  workerSyncStateInput,
  workerSyncStateOutput,
  workerRenameInput,
  workerRenameOutput,
  workerIdInput,
  workerToolCallSchema,
  workerToolResultInput,
  workerToolResultOutput,
  workerUploadRequestSchema,
  workerUploadResultInput,
  workerUploadResultOutput,
  workerFsReadRequestSchema,
  workerFsReadResultInput,
  workerFsReadResultOutput,
  // Filesystem
  fsReadInput,
  fsReadOutput,
  // Workspace
  workspaceListInput,
  workspaceListOutput,
  workspaceCreateInput,
  workspaceCreateOutput,
  workspaceRenameInput,
  workspaceRenameOutput,
  workspaceSetConfigInput,
  workspaceSetConfigOutput,
  workspaceSessionsInput,
  workspaceSessionsOutput,
  workspaceEnsureDefaultInput,
  workspaceEnsureDefaultOutput,
  workspaceOnEventsInput,
  workspaceEventSchema,
  // Provider
  providerListProvidersOutput,
  providerListModelsInput,
  providerListModelsOutput,
  // Auth
  authCreatePairingCodeInput,
  authCreatePairingCodeOutput,
  authRedeemPairingCodeInput,
  authRedeemPairingCodeOutput,
  authListApiKeysOutput,
  authRevokeApiKeyInput,
  authRevokeApiKeyOutput,
  // File transfer
  fileUploadInput,
  fileUploadOutput,
  // Plugin
  pluginCallInput,
  pluginCallOutput,
  pluginListOutput,
} from "./schemas.js";

export const contract = {
  session: {
    create: oc.input(sessionCreateInput).output(sessionCreateOutput),
    list: oc.input(sessionListInput).output(sessionListOutput),
    load: oc.input(sessionLoadInput).output(sessionLoadOutput),
    delete: oc.input(sessionDeleteInput).output(sessionDeleteOutput),
    rename: oc.input(sessionRenameInput).output(sessionRenameOutput),
  },
  agent: {
    list: oc.output(agentListOutput),
    prompt: oc.input(agentPromptInput).output(agentPromptOutput),
    shellExec: oc.input(agentShellExecInput).output(agentShellExecOutput),
    abort: oc.input(agentAbortInput).output(agentAbortOutput),
    status: oc.input(agentStatusInput).output(agentStatusOutput),
    onEvents: oc.input(agentOnEventsInput).output(eventIterator(agentEventSchema)),
  },
  tool: {
    list: oc.input(toolListInput).output(toolListOutput),
    approve: oc.input(toolApproveInput).output(toolApproveOutput),
    deny: oc.input(toolDenyInput).output(toolDenyOutput),
  },
  worker: {
    register: oc.input(workerRegisterInput).output(workerRegisterOutput),
    rename: oc.input(workerRenameInput).output(workerRenameOutput),
    syncState: oc.input(workerSyncStateInput).output(workerSyncStateOutput),
    onToolCall: oc.input(workerIdInput).output(eventIterator(workerToolCallSchema)),
    toolResult: oc.input(workerToolResultInput).output(workerToolResultOutput),
    onUpload: oc.input(workerIdInput).output(eventIterator(workerUploadRequestSchema)),
    uploadResult: oc.input(workerUploadResultInput).output(workerUploadResultOutput),
    onFsRead: oc.input(workerIdInput).output(eventIterator(workerFsReadRequestSchema)),
    fsReadResult: oc.input(workerFsReadResultInput).output(workerFsReadResultOutput),
  },
  fs: {
    read: oc.input(fsReadInput).output(fsReadOutput),
    upload: oc.input(fileUploadInput).output(fileUploadOutput),
  },
  workspace: {
    list: oc.input(workspaceListInput).output(workspaceListOutput),
    create: oc.input(workspaceCreateInput).output(workspaceCreateOutput),
    rename: oc.input(workspaceRenameInput).output(workspaceRenameOutput),
    setConfig: oc.input(workspaceSetConfigInput).output(workspaceSetConfigOutput),
    sessions: oc.input(workspaceSessionsInput).output(workspaceSessionsOutput),
    ensureDefault: oc.input(workspaceEnsureDefaultInput).output(workspaceEnsureDefaultOutput),
    onEvents: oc.input(workspaceOnEventsInput).output(eventIterator(workspaceEventSchema)),
  },
  auth: {
    createPairingCode: oc.input(authCreatePairingCodeInput).output(authCreatePairingCodeOutput),
    redeemPairingCode: oc.input(authRedeemPairingCodeInput).output(authRedeemPairingCodeOutput),
    listApiKeys: oc.output(authListApiKeysOutput),
    revokeApiKey: oc.input(authRevokeApiKeyInput).output(authRevokeApiKeyOutput),
  },
  provider: {
    listProviders: oc.output(providerListProvidersOutput),
    listModels: oc.input(providerListModelsInput).output(providerListModelsOutput),
  },
  plugin: {
    list: oc.output(pluginListOutput),
    query: oc.input(pluginCallInput).output(pluginCallOutput),
    mutate: oc.input(pluginCallInput).output(pluginCallOutput),
  },
};
