#!/usr/bin/env bun

import path from "path";
import type { BunPlugin } from "bun";

const dir = path.resolve(import.meta.dirname, "..");
process.chdir(dir);

// ---------------------------------------------------------------------------
// Plugins
// ---------------------------------------------------------------------------

/** Replaces optional dev-only imports with empty modules so the bundler doesn't choke. */
const stubPlugin: BunPlugin = {
  name: "stub-optional",
  setup(build) {
    build.onResolve({ filter: /^react-devtools-core$/ }, () => ({
      namespace: "stub",
      path: "react-devtools-core",
    }));
    build.onLoad({ filter: /.*/, namespace: "stub" }, () => ({
      contents: "export default {}",
      loader: "js",
    }));
  },
};

// ---------------------------------------------------------------------------
// Component definitions
// ---------------------------------------------------------------------------

const components = {
  server: {
    entrypoint: "./packages/server/src/main.ts",
    binary: "molf-server",
  },
  worker: {
    entrypoint: "./packages/worker/src/index.ts",
    binary: "molf-worker",
  },
  tui: {
    entrypoint: "./packages/client-tui/src/index.ts",
    binary: "molf-tui",
  },
  telegram: {
    entrypoint: "./packages/client-telegram/src/index.ts",
    binary: "molf-telegram",
  },
} as const;

type Component = keyof typeof components;

// ---------------------------------------------------------------------------
// Platform definitions
// ---------------------------------------------------------------------------

interface Platform {
  os: string;
  arch: "x64" | "arm64";
}

const allPlatforms: Platform[] = [
  { os: "linux", arch: "x64" },
  { os: "linux", arch: "arm64" },
  { os: "darwin", arch: "arm64" },
];

function bunTarget(p: Platform): string {
  return `bun-${p.os}-${p.arch}`;
}

function platformLabel(p: Platform): string {
  return `${p.os}-${p.arch}`;
}

function isCurrentPlatform(p: Platform): boolean {
  return p.os === process.platform && p.arch === process.arch;
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArg(name: string): string | undefined {
  const eqFlag = process.argv.find((a) => a.startsWith(`--${name}=`));
  if (eqFlag) return eqFlag.split("=").slice(1).join("=");
  const idx = process.argv.indexOf(`--${name}`);
  return idx !== -1 ? process.argv[idx + 1] : undefined;
}

function parseList(name: string, valid: Record<string, unknown>): string[] | undefined {
  const raw = parseArg(name);
  if (!raw) return undefined;
  return raw.split(",").map((v) => {
    const trimmed = v.trim();
    if (!(trimmed in valid)) {
      console.error(`Unknown ${name}: ${trimmed}. Valid: ${Object.keys(valid).join(", ")}`);
      process.exit(1);
    }
    return trimmed;
  });
}

const singleFlag = process.argv.includes("--single");
const selectedComponents = (parseList("target", components) ?? Object.keys(components)) as Component[];

const platformMap = Object.fromEntries(allPlatforms.map((p) => [platformLabel(p), p]));
const selectedPlatforms: Platform[] = singleFlag
  ? allPlatforms.filter(isCurrentPlatform)
  : (parseList("platform", platformMap)?.map((k) => platformMap[k]!) ?? allPlatforms);

if (selectedPlatforms.length === 0) {
  console.error("No platforms selected. Current platform not in supported list.");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Fetch models.dev snapshot for bundling
// ---------------------------------------------------------------------------

const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch("https://models.dev/api.json").then((r) => r.text());

await Bun.write(
  path.join(dir, "packages/agent-core/src/providers/models-snapshot.ts"),
  `// Auto-generated by build.ts — do not edit\nexport const snapshot = ${modelsData} as const;\n`,
);
console.log("Generated models-snapshot.ts");

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

await Bun.$`rm -rf dist`;

let built = 0;

for (const platform of selectedPlatforms) {
  const label = platformLabel(platform);
  const distDir = `dist/${label}`;
  await Bun.$`mkdir -p ${distDir}`;

  for (const name of selectedComponents) {
    const { entrypoint, binary } = components[name];
    console.log(`Building ${binary} (${label})`);

    const result = await Bun.build({
      entrypoints: [entrypoint],
      plugins: [stubPlugin],
      compile: {
        target: bunTarget(platform) as any,
        outfile: `${distDir}/${binary}`,
      },
    });

    if (!result.success) {
      console.error(`Build failed for ${binary} (${label}):`);
      for (const log of result.logs) {
        console.error(log);
      }
      process.exit(1);
    }

    console.log(`  ✓ ${distDir}/${binary}`);
    built++;
  }
}

// ---------------------------------------------------------------------------
// Package
// ---------------------------------------------------------------------------

console.log("\nPackaging...");

for (const platform of selectedPlatforms) {
  const label = platformLabel(platform);
  const distDir = `dist/${label}`;
  const archive = `dist/molf-${label}.tar.gz`;
  await Bun.$`tar -czf ${archive} -C ${distDir} .`;
  const size = Bun.file(archive).size;
  console.log(`  ✓ ${archive} (${(size / 1024 / 1024).toFixed(1)} MB)`);
}

console.log(`\nDone. Built ${built} binary(ies), ${selectedPlatforms.length} archive(s).`);
