import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, "../src/providers/models-snapshot.ts");
const MODELS_DEV_URL = "https://models.dev/api.json";
const TIMEOUT_MS = 5_000;

async function main() {
  let json: string;

  const envJson = process.env.MODELS_DEV_API_JSON;
  if (envJson) {
    console.log("Reading models catalog from MODELS_DEV_API_JSON env var");
    json = envJson;
  } else {
    console.log(`Fetching models catalog from ${MODELS_DEV_URL}...`);
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const res = await fetch(MODELS_DEV_URL, { signal: controller.signal });
      if (!res.ok) {
        throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      }
      json = await res.text();
    } finally {
      clearTimeout(timeout);
    }
  }

  // Validate it's valid JSON
  const data = JSON.parse(json);

  const content = `// Auto-generated by scripts/generate-snapshot.ts -- do not edit
export const snapshot: Record<string, unknown> = ${JSON.stringify(data)};
`;

  await writeFile(OUTPUT, content, "utf-8");
  console.log(`Written models snapshot to ${OUTPUT}`);
}

main().catch((err) => {
  console.error(`Failed to generate models snapshot: ${err.message}`);
  process.exit(1);
});
